Python Handson Rakbackend11

In [1]:
9+5

14

In [2]:
# variable assigment
x=1.0
type(x)

float

In [3]:
x=9
type(x)

int

In [4]:
# string
str='harry'

In [5]:
str

'harry'

In [6]:
t=True
type(t)

bool

In [7]:
x= 3 + 4j

In [8]:
print(type(x))

<class 'complex'>


In [9]:
print(x.real,x.imag)

3.0 4.0


In [10]:
m=1
y=1.0


In [11]:
type(m) is float

False

In [12]:
type(y) is int

False

In [13]:
type(m) is int

True

In [14]:
10+3

13

In [15]:
10-3

7

In [16]:
10*3

30

In [19]:
10//3  # integer division

3

In [20]:
10%3  # modulus division

1

In [22]:
10/3  # float division

3.3333333333333335

In [23]:
True and False


False

In [24]:
True or False

True

In [25]:
not True

False

In [26]:
a=10
b=20


In [27]:
a>=b

False

In [28]:
a<b

True

In [29]:
a==b

False

In [30]:
a>b

False

In [31]:
a<=b

True

In [32]:
l=[1,2]
m=[1,2]

In [33]:
l==m

True

In [34]:
l is m

False

In [35]:
l and m

[1, 2]

In [36]:
a=10
b=20

In [37]:
a&b

0

In [38]:
a^b

30

In [39]:
a | b

30

In [40]:
a=10
b=20
if a>b:
    print("a is greater")
else:
    print("B is greater")

B is greater


In [41]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [42]:
n=input("enter the name")
print(n)

<Future pending>


enter the name harry


In [44]:
n1=int(input("enter the age"))
print(n1)

<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'Future'

enter the age 20


In [45]:
n=list(map(int,input().split()))
print(n)

<class 'AttributeError'>: 'Future' object has no attribute 'split'

 1 2 3 4 4 6 6 7


In [52]:
m="Hello"
print(f"%s world"%m)

Hello world


In [2]:
print("name"*3)

namenamename


In [4]:
#Data Structures
# List

In [5]:
l=[1,"hello",1.0]

In [6]:
l

[1, 'hello', 1.0]

In [7]:
start = 1
stop = 50
step =3
list(range(start, stop, step))


[1, 4, 7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]

In [8]:
range(1,5,2)

range(1, 5, 2)

In [15]:
l=[1,3,2,4,8.0]

In [11]:
l=l.sort()

In [13]:
print(l)

None


In [16]:
l=sorted(l)

In [17]:
l

[1, 2, 3, 4, 8.0]

In [18]:
m=[1.0,1,2.0,2]

In [19]:
m=sorted(m)

In [20]:
m

[1.0, 1, 2.0, 2]

In [21]:
s="Hello Wold"

In [22]:
print(list(s))

['H', 'e', 'l', 'l', 'o', ' ', 'W', 'o', 'l', 'd']


In [23]:
a1= [10,20,30,40,50]

In [24]:
a1.append(200)

In [25]:
a1

[10, 20, 30, 40, 50, 200]

In [26]:
a1.pop()

200

In [27]:
a1

[10, 20, 30, 40, 50]

In [29]:
a1.pop(2)

30

In [30]:
a1

[10, 20, 40, 50]

In [31]:
a1.insert(1,300)

In [32]:
a1

[10, 300, 20, 40, 50]

In [33]:
a1.remove(20)

In [34]:
a1

[10, 300, 40, 50]

In [35]:
a1.reverse()

In [36]:
a1

[50, 40, 300, 10]

In [37]:
a1.index(300)

2

In [38]:
a1.sort()

In [39]:
a1

[10, 40, 50, 300]

In [40]:
a1.index(300)

3

In [42]:
a1.extend([24,55,22])

In [43]:
a1

[10, 40, 50, 300, 24, 55, 22]

In [44]:
a1[4]=100

In [45]:
a1

[10, 40, 50, 300, 100, 55, 22]

In [46]:
a1[1:3]=[190,220]

In [47]:
a1

[10, 190, 220, 300, 100, 55, 22]

In [48]:
del a1[2]

In [49]:
a1

[10, 190, 300, 100, 55, 22]

In [52]:
lst1 = [0, 1, 22]
lst2 = [3, 4, 5]
list3 = lst1 + lst2

In [53]:
list3

[0, 1, 22, 3, 4, 5]

In [54]:
22 in list3

True

In [55]:
0.5 in list3

False

In [56]:
p=(1,2)

In [58]:
type(p)

tuple

In [59]:
k=(1.0,9.0)

In [60]:
m=p+k

In [61]:
m

(1, 2, 1.0, 9.0)

In [62]:
len(m)

4

In [63]:
9.0 in m

True

In [64]:
t=(1,1,1,1,5,4)

In [65]:
t.count(1)

4

In [66]:
t.index(1)

0

In [67]:
t.index(5)

4

In [68]:
tup = ('physics', 'chemistry', 1997, 2000);
tup

('physics', 'chemistry', 1997, 2000)

In [1]:
my_set = set([1,2,3,2])
my_set

{1, 2, 3}

In [2]:
new_set=my_set.copy()

In [3]:
new_set

{1, 2, 3}

In [4]:
new_set.add(100)

In [5]:
new_set

{1, 2, 3, 100}

In [6]:
A = {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}

In [7]:
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [8]:
A.intersection(B)

{4, 5}

In [9]:
A.difference(B)

{1, 2, 3}

In [10]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [11]:
v={1,1,2,2,2,1,3,4}

In [12]:
fswt=frozenset(v)

In [13]:
fswt

frozenset({1, 2, 3, 4})

In [14]:
s={
    "name":"Harry",
    "age":20
}

In [15]:
s

{'name': 'Harry', 'age': 20}

In [16]:
s['name']

'Harry'

In [17]:
s['age']

20

In [18]:
s['class']=10


In [19]:
s

{'name': 'Harry', 'age': 20, 'class': 10}

In [20]:
s.get('name')

'Harry'

In [21]:
s.items()

dict_items([('name', 'Harry'), ('age', 20), ('class', 10)])

In [23]:
s.values()

dict_values(['Harry', 20, 10])

In [24]:
s.keys()

dict_keys(['name', 'age', 'class'])

In [26]:
s.pop('name')

'Harry'

In [27]:
s

{'age': 20, 'class': 10}

In [28]:
x=s.copy()

In [29]:
x

{'age': 20, 'class': 10}

In [31]:
x.clear()

In [32]:
x

{}

In [33]:
import math

In [34]:
math.sqrt(100)

10.0

In [35]:
math.cos(20)

0.40808206181339196

In [36]:
math.sin(11)

-0.9999902065507035

In [37]:
math.ceil(11.3)

12

In [38]:
math.floor(11.9)

11

In [42]:
round(11.445,2)

11.45

In [44]:
abs(-88)

88

In [45]:
math.exp(2)

7.38905609893065

In [46]:
s4 = "1234"
s4.isdigit()

True

In [47]:
import re

In [48]:
txt = "Cricket has 11 players, they play for 5 days "
re.findall("la", txt)

['la', 'la']

In [49]:
import re
re.search('dog', 'dog cat dog')

<re.Match object; span=(0, 3), match='dog'>

In [51]:
import re
pattern = re.compile("^(\d{2})-(\d{2})-(\d{4})$")
valid = pattern.match("00-01-2000")
if valid:
    print ("Valid date!")
else:
    print("Invalid Date!")

Valid date!


In [53]:
str = 'My email is abc123@google.com, His email is cde@gmail.com Her mail is sss@dasd.in'
emails = re.findall(r'[\w\.-]+@[\w\.-]+', str)
for email in emails:
    print(email)



abc123@google.com
cde@gmail.com
sss@dasd.in


In [54]:
def name():
    print('Hello')

In [55]:
name()

Hello


In [56]:
def name(x):
    return x

In [57]:
name(1)

1

In [58]:
name('Hrar')

'Hrar'

In [3]:
import numpy as np
a = np.array([1,2])
b = np.array([2,1])

In [60]:
np.sum(a*b)

4

In [63]:
np.size(a)

2

In [64]:
a[1]

2

In [65]:
a = np.array([[10, 20, 30], [40, 50, 60]])

In [66]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [67]:
a[1]

array([40, 50, 60])

In [68]:
a[1][2]

60

In [70]:
a.shape

(2, 3)

In [71]:
c=np.array([(1,2,3), (4,5,6),(7,8,9),(10,11,12)])

In [72]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [73]:
c.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [74]:
c.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
np.zeros(3)

array([0., 0., 0.])

In [77]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.full((3,3), 8)

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [79]:
np.ones(2)

array([1., 1.])

In [80]:
np.ones((1,6))

array([[1., 1., 1., 1., 1., 1.]])

In [81]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [82]:
np.random.random((2,2))

array([[0.60372221, 0.67254836],
       [0.29515111, 0.16998897]])

In [83]:
np.random.random((2,2))

array([[0.28089588, 0.80002357],
       [0.40719193, 0.47463795]])

In [84]:
s = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(s)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
s[1:2,:]

array([[5, 6, 7, 8]])

In [87]:
s[:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [1]:
data=[1,2,3,55,6,65]

In [4]:
np.mean(data)

22.0

In [5]:
np.median(data)

4.5

In [6]:
np.std(data)

27.067816067549053

In [7]:
np.var(data)

732.6666666666666

In [8]:
np.quantile(data,0.8)

55.0

In [9]:
import pandas as pd

In [10]:
data=pd.Series([1,2,3,4,5])

In [11]:
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [12]:
data=pd.Series(['a','b','c','d'])

In [13]:
data

0    a
1    b
2    c
3    d
dtype: object

In [15]:
data.values

array(['a', 'b', 'c', 'd'], dtype=object)

In [16]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
mymarks = pd.Series([178,200,199,197], index=['maths', 'chemistry', 'biology', 'physics'])

In [19]:
mymarks

maths        178
chemistry    200
biology      199
physics      197
dtype: int64

In [20]:
mymarks['biology']

199

In [21]:
mymarks[mymarks>100]

maths        178
chemistry    200
biology      199
physics      197
dtype: int64

In [22]:
mymarks[mymarks>180]

chemistry    200
biology      199
physics      197
dtype: int64

In [23]:
mymarks_dic=mymarks.to_dict()

In [24]:
mymarks_dic

{'maths': 178, 'chemistry': 200, 'biology': 199, 'physics': 197}

In [25]:
mydata={
    "maths":200,
    "chemistry":300,
    "social":240
}

In [32]:
newsubs = ['biology','chemistry','maths', 'physics', 'english']
newvals = pd.Series(mymarks_dic, index=newsubs)
newvals

biology      199.0
chemistry    200.0
maths        178.0
physics      197.0
english        NaN
dtype: float64

In [33]:
newvals.isnull()

biology      False
chemistry    False
maths        False
physics      False
english       True
dtype: bool

In [34]:
newvals.isnull().sum()

1

In [35]:
newvals.notnull().sum()

4

In [36]:
newvals.dropna()

biology      199.0
chemistry    200.0
maths        178.0
physics      197.0
dtype: float64

In [33]:
import numpy as np
x = np.array([1, 2])
print(x.dtype)

int64


In [2]:
y=np.array([1.0,2.0,3.0])

In [3]:
y.dtype

dtype('float64')

In [4]:
mn=np.array(['a','y','g'])

In [5]:
mn.dtype

dtype('<U1')

In [6]:
x='Hello World'

In [7]:
np.char.upper(x)

array('HELLO WORLD', dtype='<U11')

In [9]:
np.char.lower(x)

array('hello world', dtype='<U11')

In [10]:
np.char.title(x)

array('Hello World', dtype='<U11')

In [12]:
np.char.split(x)

array(list(['Hello', 'World']), dtype=object)

In [2]:
pip install seaborn

     |████████████████████████████████| 292 kB 4.5 MB/s            
Note: you may need to restart the kernel to use updated packages.


In [3]:
import seaborn as sns

In [4]:
dataset=sns.load_dataset('titanic')

In [5]:
dataset.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [8]:
dataset.shape

(891, 15)

In [9]:
len(dataset)

891

In [10]:
dataset['embark_town']

0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...     
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object

In [11]:
dataset['embark_town'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: embark_town, Length: 891, dtype: bool

In [12]:
dataset['embark_town'].isnull().sum()

2

In [13]:
dataset['Sex_binary']=dataset['sex'].map({'female':0,'male':1})

In [14]:
dataset.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  Sex_binary  
0    man        True  NaN  Southampton    no  False           1  
1  woman       False    C    Cherbourg   yes  False           0  
2  woman       False  NaN  Southampton   yes   True           0  
3  woman       False    C  Southampton   yes  False           0  
4    man        True  NaN  Southampton    no   True           1

In [15]:
dataset.fare=dataset.fare.map(lambda x: x*0.5)

In [16]:
dataset.head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
0         0       3    male  22.0      1      0   3.62500        S  Third   
1         1       1  female  38.0      1      0  35.64165        C  First   
2         1       3  female  26.0      0      0   3.96250        S  Third   
3         1       1  female  35.0      1      0  26.55000        S  First   
4         0       3    male  35.0      0      0   4.02500        S  Third   

     who  adult_male deck  embark_town alive  alone  Sex_binary  
0    man        True  NaN  Southampton    no  False           1  
1  woman       False    C    Cherbourg   yes  False           0  
2  woman       False  NaN  Southampton   yes   True           0  
3  woman       False    C  Southampton   yes  False           0  
4    man        True  NaN  Southampton    no   True           1

In [19]:
dataset.who.isnull().sum()

0

In [21]:
dataset.who.unique()

array(['man', 'woman', 'child'], dtype=object)

In [22]:
dataset.who=dataset.who.map({'man':1,'woman':0,'child':2} )

In [23]:
dataset.head()

survived  pclass     sex   age  sibsp  parch      fare embarked  class  \
0         0       3    male  22.0      1      0   3.62500        S  Third   
1         1       1  female  38.0      1      0  35.64165        C  First   
2         1       3  female  26.0      0      0   3.96250        S  Third   
3         1       1  female  35.0      1      0  26.55000        S  First   
4         0       3    male  35.0      0      0   4.02500        S  Third   

   who  adult_male deck  embark_town alive  alone  Sex_binary  
0    1        True  NaN  Southampton    no  False           1  
1    0       False    C    Cherbourg   yes  False           0  
2    0       False  NaN  Southampton   yes   True           0  
3    0       False    C  Southampton   yes  False           0  
4    1        True  NaN  Southampton    no   True           1

In [26]:
dataset['class'].unique()

['Third', 'First', 'Second']
Categories (3, object): ['Third', 'First', 'Second']

In [27]:
dataset['class']=dataset['class'].map({'First':1,'Second':2,'Third':3})

In [28]:
dataset.head()

survived  pclass     sex   age  sibsp  parch      fare embarked class  who  \
0         0       3    male  22.0      1      0   3.62500        S     3    1   
1         1       1  female  38.0      1      0  35.64165        C     1    0   
2         1       3  female  26.0      0      0   3.96250        S     3    0   
3         1       1  female  35.0      1      0  26.55000        S     1    0   
4         0       3    male  35.0      0      0   4.02500        S     3    1   

   adult_male deck  embark_town alive  alone  Sex_binary  
0        True  NaN  Southampton    no  False           1  
1       False    C    Cherbourg   yes  False           0  
2       False  NaN  Southampton   yes   True           0  
3       False    C  Southampton   yes  False           0  
4        True  NaN  Southampton    no   True           1

In [29]:
dataset['embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [30]:
dataset.dropna()

survived  pclass     sex   age  sibsp  parch      fare embarked class  \
1           1       1  female  38.0      1      0  35.64165        C     1   
3           1       1  female  35.0      1      0  26.55000        S     1   
6           0       1    male  54.0      0      0  25.93125        S     1   
10          1       3  female   4.0      1      1   8.35000        S     3   
11          1       1  female  58.0      0      0  13.27500        S     1   
..        ...     ...     ...   ...    ...    ...       ...      ...   ...   
871         1       1  female  47.0      1      1  26.27710        S     1   
872         0       1    male  33.0      0      0   2.50000        S     1   
879         1       1  female  56.0      0      1  41.57915        C     1   
887         1       1  female  19.0      0      0  15.00000        S     1   
889         1       1    male  26.0      0      0  15.00000        C     1   

     who  adult_male deck  embark_town alive  alone  Sex_binary  
1      0       False    C    Cherbourg   yes  False           0  
3      0       False    C  Southampton   yes  False           0  
6      1        True    E  Southampton    no   True           1  
10     2       False    G  Southampton   yes  False           0  
11     0       False    C  Southampton   yes   True           0  
..   ...         ...  ...          ...   ...    ...         ...  
871    0       False    D  Southampton   yes  False           0  
872    1        True    B  Southampton    no   True           1  
879    0       False    C    Cherbourg   yes  False           0  
887    0       False    B  Southampton   yes   True           0  
889    1        True    C    Cherbourg   yes   True           1  

[182 rows x 16 columns]

In [31]:
dataset.head()

survived  pclass     sex   age  sibsp  parch      fare embarked class  who  \
0         0       3    male  22.0      1      0   3.62500        S     3    1   
1         1       1  female  38.0      1      0  35.64165        C     1    0   
2         1       3  female  26.0      0      0   3.96250        S     3    0   
3         1       1  female  35.0      1      0  26.55000        S     1    0   
4         0       3    male  35.0      0      0   4.02500        S     3    1   

   adult_male deck  embark_town alive  alone  Sex_binary  
0        True  NaN  Southampton    no  False           1  
1       False    C    Cherbourg   yes  False           0  
2       False  NaN  Southampton   yes   True           0  
3       False    C  Southampton   yes  False           0  
4        True  NaN  Southampton    no   True           1

In [34]:
dataset.fare.apply(np.sqrt).head()

0    1.903943
1    5.970063
2    1.990603
3    5.152669
4    2.006240
Name: fare, dtype: float64

In [35]:
dataset[['fare','age']].applymap(np.sqrt).head()

fare       age
0  1.903943  4.690416
1  5.970063  6.164414
2  1.990603  5.099020
3  5.152669  5.916080
4  2.006240  5.916080

In [36]:
dataset[dataset['sex'] == 'male'].head()

survived  pclass   sex   age  sibsp  parch      fare embarked class  who  \
0         0       3  male  22.0      1      0   3.62500        S     3    1   
4         0       3  male  35.0      0      0   4.02500        S     3    1   
5         0       3  male   NaN      0      0   4.22915        Q     3    1   
6         0       1  male  54.0      0      0  25.93125        S     1    1   
7         0       3  male   2.0      3      1  10.53750        S     3    2   

   adult_male deck  embark_town alive  alone  Sex_binary  
0        True  NaN  Southampton    no  False           1  
4        True  NaN  Southampton    no   True           1  
5        True  NaN   Queenstown    no   True           1  
6        True    E  Southampton    no   True           1  
7       False  NaN  Southampton    no  False           1

In [37]:
dataset[dataset['embark_town'] == 'Southampton'].head()

survived  pclass     sex   age  sibsp  parch      fare embarked class  who  \
0         0       3    male  22.0      1      0   3.62500        S     3    1   
2         1       3  female  26.0      0      0   3.96250        S     3    0   
3         1       1  female  35.0      1      0  26.55000        S     1    0   
4         0       3    male  35.0      0      0   4.02500        S     3    1   
6         0       1    male  54.0      0      0  25.93125        S     1    1   

   adult_male deck  embark_town alive  alone  Sex_binary  
0        True  NaN  Southampton    no  False           1  
2       False  NaN  Southampton   yes   True           0  
3       False    C  Southampton   yes  False           0  
4        True  NaN  Southampton    no   True           1  
6        True    E  Southampton    no   True           1

In [40]:
dataset.describe()

survived      pclass         age       sibsp       parch        fare  \
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000   
mean     0.383838    2.308642   29.699118    0.523008    0.381594   16.102104   
std      0.486592    0.836071   14.526497    1.102743    0.806057   24.846714   
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000   
25%      0.000000    2.000000   20.125000    0.000000    0.000000    3.955200   
50%      0.000000    3.000000   28.000000    0.000000    0.000000    7.227100   
75%      1.000000    3.000000   38.000000    1.000000    0.000000   15.500000   
max      1.000000    3.000000   80.000000    8.000000    6.000000  256.164600   

              who  Sex_binary  
count  891.000000  891.000000  
mean     0.789001    0.647587  
std      0.594291    0.477990  
min      0.000000    0.000000  
25%      0.000000    0.000000  
50%      1.000000    1.000000  
75%      1.000000    1.000000  
max      2.000000    1.000000

In [42]:
dataset["pclass"].value_counts(ascending=True)

2    184
1    216
3    491
Name: pclass, dtype: int64

In [43]:
dataset["sex"].value_counts(ascending=True)

female    314
male      577
Name: sex, dtype: int64

In [44]:
dataset['fare'].max()

256.1646

In [45]:
dataset['fare'].min()

0.0

In [46]:
dataset['fare'].std()

24.84671429859045

In [47]:
dataset['fare'].var()

617.359211435779